prompt_params:
  log_file_path: "prompt.log"

preprocess_params:
  log_file_path: "docs_preprocess.log"
  chunk_size: 1000
  chunk_overlap: 150

create_agent_params:
  log_file_path: "agent.log"

agent_bot_params:
  log_file_path: "agent_bot.log"
  chat_history_limit: 5 

server_params:
  log_file_path: "server.log"

pinecone_memory_params:
  log_file_path: "pinecone_memory.log"

mangodb_params:
  log_file_path: "mongodb.log"