session_prompt_params:
  log_file_path: "session_prompt.log"

preprocess_params:
  log_file_path: "docs_preprocess.log"
  chunk_size: 1000
  chunk_overlap: 150

create_agent_params:
  log_file_path: "agent.log"

redis_params:
  log_file_path: "redisdb.log"

rag_chatbot_params:
  log_file_path: "rag_chatbot.log"
  chat_history_limit: 5 

server_params:
  log_file_path: "server.log"

pinecone_memory_params:
  log_file_path: "pinecone_memory.log"

mangodb_params:
  log_file_path: "mongodb.log"